/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ExplorerIndexRouteImport } from './routes/explorer.index'
import { Route as ExplorerBodyRouteImport } from './routes/explorer.$body'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerIndexRoute = ExplorerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExplorerRoute,
} as any)
const ExplorerBodyRoute = ExplorerBodyRouteImport.update({
  id: '/$body',
  path: '/$body',
  getParentRoute: () => ExplorerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRouteWithChildren
  '/missions': typeof MissionsRoute
  '/research': typeof ResearchRoute
  '/explorer/$body': typeof ExplorerBodyRoute
  '/explorer/': typeof ExplorerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/missions': typeof MissionsRoute
  '/research': typeof ResearchRoute
  '/explorer/$body': typeof ExplorerBodyRoute
  '/explorer': typeof ExplorerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRouteWithChildren
  '/missions': typeof MissionsRoute
  '/research': typeof ResearchRoute
  '/explorer/$body': typeof ExplorerBodyRoute
  '/explorer/': typeof ExplorerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explorer'
    | '/missions'
    | '/research'
    | '/explorer/$body'
    | '/explorer/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/missions' | '/research' | '/explorer/$body' | '/explorer'
  id:
    | '__root__'
    | '/'
    | '/explorer'
    | '/missions'
    | '/research'
    | '/explorer/$body'
    | '/explorer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExplorerRoute: typeof ExplorerRouteWithChildren
  MissionsRoute: typeof MissionsRoute
  ResearchRoute: typeof ResearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer/': {
      id: '/explorer/'
      path: '/'
      fullPath: '/explorer/'
      preLoaderRoute: typeof ExplorerIndexRouteImport
      parentRoute: typeof ExplorerRoute
    }
    '/explorer/$body': {
      id: '/explorer/$body'
      path: '/$body'
      fullPath: '/explorer/$body'
      preLoaderRoute: typeof ExplorerBodyRouteImport
      parentRoute: typeof ExplorerRoute
    }
  }
}

interface ExplorerRouteChildren {
  ExplorerBodyRoute: typeof ExplorerBodyRoute
  ExplorerIndexRoute: typeof ExplorerIndexRoute
}

const ExplorerRouteChildren: ExplorerRouteChildren = {
  ExplorerBodyRoute: ExplorerBodyRoute,
  ExplorerIndexRoute: ExplorerIndexRoute,
}

const ExplorerRouteWithChildren = ExplorerRoute._addFileChildren(
  ExplorerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExplorerRoute: ExplorerRouteWithChildren,
  MissionsRoute: MissionsRoute,
  ResearchRoute: ResearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
